apiVersion: v1
kind: Service
metadata:
  name: go-server
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: go-server
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-server
  labels:
    app: go-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      labels:
        app: go-server
    spec:
      imagePullSecrets:
        - name: liuma-registry
      containers:
        - name: go-server
          image: registry.cn-qingdao.aliyuncs.com/anthhub/go-demo:latest
          resources:
            limits:
              memory: "32Mi"
              cpu: "0.2"
          ports:
            - name: web
              containerPort: 8000
